const ORION = {
  ENTITIES_CONTROLLER: 'entities',
  ATTRIBUTES_CONTROLLER: 'attrs',
  ENTITY_TYPE_TRAVEL: 'Travel',
  ENTITY_TYPE_EXPENSE: 'Expense',
  ENTITY_TYPE_USER: 'User',
  ATTRIBUTE_TYPE_STRING: 'Text',
  ATTRIBUTE_TYPE_NUMBER: 'Float',
  ATTRIBUTE_TYPE_DATE: 'Datetime',
  ATTRIBUTE_TYPE_ARRAY: 'StructuredValue',
  ATTRIBUTE_TYPE_GEOLOCATION: 'geo:point',
  ATTRIBUTE_NAME_EXPENSES: 'expenses',
  DEFAULT_STRING: 'PLACEHOLDER',
  DEFAULT_DATE: '1970-01-01',
};

module.exports = { ORION };
